name: Go

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Go lang
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.13
    - name: Build the content
      run: |
        ./blog
      shell: bash
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        path: public
        FOLDER: public
        BRANCH: master
            