[user]
name="Darshan Sharma"
email="thedarshansharma@gmail.com"
[site]
name="Darshan Sharma. Senior Software Engineer"
url="https://darshansharma.xyz"
description="Darshan Sharma. Senior Software Engineer"
[feed]
add="""<p>Got comments? Send them to me via <a href='https://twitter.com/darshansharma_'>Twitter</a>.</p>"""
enableComments="true"